// Code generated by Arduino IoT Cloud, DO NOT EDIT.
/*
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "17209fad-6078-45ce-94da-3c28471c8f5b";

const char SSID[]               = Piumal;    // Network SSID (name)
const char PASS[]               = piumal@m;    // Network pass  word (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = L9K53NB6CYYUGYUQKHFA;    // Secret device password

void onNFCChange();
void onOLEDdisplayChange();
void onLedIndicator1Change();
void onLedIndicator2Change();

String nFC;
String oLEDdisplay;
CloudLight ledIndicator1;
CloudLight ledIndicator2;
CloudTemperatureSensor temperature;


void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(nFC, READWRITE, ON_CHANGE, onNFCChange);
  ArduinoCloud.addProperty(oLEDdisplay, READWRITE, ON_CHANGE, onOLEDdisplayChange);
  ArduinoCloud.addProperty(ledIndicator1, READWRITE, ON_CHANGE, onLedIndicator1Change);
  ArduinoCloud.addProperty(ledIndicator2, READWRITE, ON_CHANGE, onLedIndicator2Change);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS); 
*/